kubevirt/web-ui-components

.travis.yml
an example output can be seen at https://github.com/ohadlevy/web-ui/pull/1
(linking to https://travis-ci.org/ohadlevy/web-ui/builds/423581566)
=> adds travis support

README.md
=> README: show travis status for master branch

README.md
=> README: add link to kubevirt project

.gitignore
=> gitignore: remove /build

src/components/Wizards/CreateVmWizard/CreateVmWizard.js, src/components/Wizards/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap, yarn.lock
=> CreateVmWizard: disable cancel button in the last step (fix #61)

.travis.yml, tools/travis/tasks/addGhDeployKey.js, tools/travis/tasks/deployCosmosToGhPages.js
This PR un-breaks the build and fixes the process of Cosmos deploy to `gh-pages` branch upon PR merge.
=> Ensure that ssh-agent is running on CI workers

sass/components/_NetworksTab.scss, src/components/Form/FormFactory.js, src/components/Form/tests/__snapshots__/FormFactory.test.js.snap, src/components/Table/TableFactory.js, src/components/Table/tests/TableFactory.test.js, src/components/Wizards/CreateVmWizard/BasicSettingsTab.js, src/components/Wizards/CreateVmWizard/NetworksTab.js, src/components/Wizards/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap, src/components/Wizards/CreateVmWizard/tests/__snapshots__/NetworksTab.test.js.snap, src/constants/index.js, src/k8s/mock_network/network2.template.js
depends on https://github.com/kubevirt/web-ui-components/pull/52
[storybook](https://agitated-fermi-950e49.netlify.com/?component=Wizards%2FCreateVmWizard%2Fj&fixture=namespaces)
=> Choose bootable network with dropdown

src/components/Wizard/CreateVmWizard/BasicSettingsTab.js, src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
fix for https://github.com/kubevirt/web-ui/issues/66
=> Add ids to basic settings form fields

src/components/Wizard/CreateVmWizard/CreateVmWizard.js, src/components/Wizard/CreateVmWizard/StorageTab.js, src/components/Wizard/CreateVmWizard/utils.js, src/k8s/mock_user_templates/linux.template.js, src/k8s/mock_user_templates/windows.template.js, src/k8s/request.js, src/k8s/selectors.js, src/k8s/tests/request.test.js, src/models/index.js, src/utils/selectors.js
backport https://github.com/kubevirt/web-ui-components/pull/87 to v1.3
=> import-vm-apb template is using datavolumes not pvc

package.json
This will be used for web-ui v1.3 fixes
=> Bump 0.1.7-1

src/k8s/request.js, src/k8s/tests/request.test.js
https://bugzilla.redhat.com/show_bug.cgi?id=1648245
=> Set firstBoot annotation to false if VM should start after creation

src/components/Wizard/CreateVmWizard/BasicSettingsTab.js, src/components/Wizard/CreateVmWizard/CreateVmWizard.js, src/components/Wizard/CreateVmWizard/constants.js, src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap, src/k8s/request.js, src/k8s/tests/request.test.js
backport https://github.com/kubevirt/web-ui-components/pull/91 to v1.3
=> Add configurable URL Disk size

src/components/Loading.js, src/components/Wizard/CreateVmWizard/CreateVmWizard.js, src/components/Wizard/CreateVmWizard/ResultTab.js, src/components/Wizard/CreateVmWizard/fixtures/BasicSettingsTab.fixture.js, src/components/Wizard/CreateVmWizard/fixtures/CreateVmWizard.fixture.js, src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js, src/components/Wizard/CreateVmWizard/tests/__snapshots__/ResultTab.test.js.snap, src/components/Wizard/loadingWizardTab.js, src/components/Wizard/tests/loadingWizardTab.test.js, src/components/fixtures/Loading.fixture.js, src/components/tests/Loading.test.js, src/components/tests/__snapshots__/Loading.test.js.snap
https://bugzilla.redhat.com/show_bug.cgi?id=1646950
=> Add Loading to Create VM Wizard tabs.

src/components/Form/FormFactory.js, src/components/Wizard/CreateVmWizard/BasicSettingsTab.js, src/components/Wizard/CreateVmWizard/CreateVmWizard.js, src/components/Wizard/CreateVmWizard/NetworksTab.js, src/components/Wizard/CreateVmWizard/StorageTab.js, src/components/Wizard/CreateVmWizard/strings.js, src/components/Wizard/CreateVmWizard/tests/BasicSettingsTab.test.js, src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap, src/components/Wizard/CreateVmWizard/tests/__snapshots__/NetworksTab.test.js.snap, src/constants/index.js, src/utils/strings.js, src/utils/tests/validation.test.js, src/utils/validations.js
part of https://github.com/kubevirt/web-ui/issues/92 -  we will also need to add check if VM already exists
=> Add VM name validation against DNS1123 subdomain spec

src/components/Wizard/CreateVmWizard/CreateVmWizard.js, src/components/Wizard/CreateVmWizard/constants.js, src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js, src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap, src/components/Wizard/CreateVmWizard/utils.js, src/utils/templates.js, src/utils/tests/templates.test.js
https://github.com/kubevirt/web-ui-components/issues/77
=> Use object instead of array in CreateVmWizard stepData. #77

src/components/Wizard/CreateVmWizard/BasicSettingsTab.js, src/components/Wizard/CreateVmWizard/CreateVmWizard.js, src/components/Wizard/CreateVmWizard/StorageTab.js, src/components/Wizard/CreateVmWizard/constants.js, src/components/Wizard/CreateVmWizard/fixtures/BasicSettingsTab.fixture.js, src/components/Wizard/CreateVmWizard/tests/BasicSettingsTab.test.js, src/components/Wizard/CreateVmWizard/tests/NetworksTab.test.js, src/components/Wizard/CreateVmWizard/tests/StorageTab.test.js, src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap, src/constants/index.js, src/k8s/mock_user_templates/container-cloud.mock.js, src/k8s/mock_user_templates/container-multus.mock.js, src/k8s/mock_user_templates/container.mock.js, src/k8s/request.js, src/k8s/tests/request.test.js, src/utils/templates.js, src/utils/tests/templates.test.js
kubevirt v.0.11.0 renamed registryDisk to containerDisk https://github.com/kubevirt/kubevirt/pull/1730
=> Rename registryDisk to containerDisk. #124

src/components/VmStatus/getVmStatus.js
needed for cancel migration pull request in kubevirt/web-ui
=> export isBeingMigrated function

sass/components/_VmDetails.scss, src/components/Details/VmDetails/VmDetails.js, src/components/Details/VmDetails/fixtures/VmDetails.fixture.js, src/components/Details/VmDetails/tests/VmDetails.test.js, src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap, src/utils/selectors.js, src/utils/tests/selectors.test.js
- use Row and Col components
- extract getVmIpAddresses to selectors.js
- other small fixes
=> Vm Details cleanup

src/components/Wizard/CreateVmWizard/BasicSettingsTab.js, src/components/Wizard/CreateVmWizard/strings.js, src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
https://bugzilla.redhat.com/show_bug.cgi?id=1648334
=> Add help icons to Create Vm/BasicSettings tab.

sass/components/Wizard/create-vm-wizard.scss, src/components/Form/FormFactory.js, src/components/Form/TextArea.js, src/components/Wizard/CreateVmWizard/BasicSettingsTab.js, src/components/Wizard/CreateVmWizard/constants.js, src/components/Wizard/CreateVmWizard/tests/BasicSettingsTab.test.js, src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap, src/k8s/request.js, src/k8s/request/cloudInit.js, src/k8s/request/tests/__snapshots__/cloudInit.test.js.snap, src/k8s/request/tests/cloudInit.test.js, src/k8s/tests/request.test.js, src/utils/selectors.js
implements #104 
no possibility to add files for now; only copy-paste text
- uploading a file (or multiple files) can be added in a followup
=> add custom cloud-init script to Create VM Dialog

src/components/Wizard/CreateVmWizard/StorageTab.js, src/components/Wizard/CreateVmWizard/tests/StorageTab.test.js, src/utils/strings.js, src/utils/tests/validation.test.js, src/utils/validations.js
Add DNS1123 validation to storage name.
https://bugzilla.redhat.com/show_bug.cgi?id=1659347
=> Do not allow uppercase letters in DNS1123 validation.

src/components/Details/VmDetails/VmDetails.js, src/components/Form/Dropdown.js, src/components/Form/FormFactory.js, src/components/Form/tests/__snapshots__/Dropdown.test.js.snap, src/components/Form/tests/__snapshots__/FormFactory.test.js.snap, src/components/Wizard/CreateVmWizard/NetworksTab.js, src/components/Wizard/CreateVmWizard/StorageTab.js, src/components/Wizard/CreateVmWizard/fixtures/BasicSettingsTab.fixture.js, src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap, src/constants/index.js, src/k8s/mock_templates/fedora28.mock.js, src/k8s/mock_templates/rhel-high-p.mock.js, src/k8s/mock_templates/rhel75.mock.js, src/k8s/mock_templates/ubuntu1804.mock.js, src/k8s/mock_templates/windows.mock.js, src/k8s/mock_user_templates/container-cloud.mock.js, src/k8s/mock_user_templates/container-multus.mock.js, src/k8s/mock_user_templates/container.mock.js, src/k8s/mock_user_templates/pxe-dv.mock.js, src/k8s/mock_user_templates/pxe-pvc.mock.js, src/k8s/mock_user_templates/pxe.mock.js, src/k8s/mock_user_templates/url-flavor.mock.js, src/k8s/mock_user_templates/url-nonetwork.mock.js, src/k8s/mock_user_templates/url.mock.js, src/k8s/request.js, src/k8s/selectors.js, src/k8s/tests/request.test.js, src/k8s/tests/selectors.test.js, src/utils/selectors.js
https://bugzilla.redhat.com/show_bug.cgi?id=1648335
=> Show full  OS names.

src/k8s/request.js
- fixes vm from template start up
=> fix default disk

src/components/Details/Flavor/Flavor.js, src/components/Details/Flavor/tests/__snapshots__/Flavor.test.js.snap, src/components/Details/VmDetails/VmDetails.js, src/components/Details/VmDetails/fixtures/VmDetails.fixture.js, src/components/Details/VmDetails/tests/VmDetails.test.js, src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap, src/utils/templates.js, src/utils/tests/templates.test.js
Fallback to mocked vm templates if given template is not found in kubernetes. #168
=> Fix VM Details form validity detection

src/components/CreateNicRow/CreateNicRow.js, src/components/CreateNicRow/tests/__snapshots__/CreateNicRow.test.js.snap, src/components/Table/EditableDraggableTable.js, src/components/Wizard/CreateVmWizard/NetworksTab.js, src/components/Wizard/CreateVmWizard/StorageTab.js, src/components/Wizard/CreateVmWizard/tests/StorageTab.test.js, src/components/Wizard/CreateVmWizard/tests/__snapshots__/NetworksTab.test.js.snap, src/components/Wizard/CreateVmWizard/tests/__snapshots__/StorageTab.test.js.snap, src/utils/tests/utils.test.js, src/utils/utils.js
Do not allow changing MAC address for Pod network.
https://github.com/kubevirt/web-ui-components/issues/132 https://github.com/kubevirt/web-ui-components/issues/176
=> Table renderConfig is now function, not static declaration.

src/constants/index.js, src/k8s/mock_templates/fedora28.mock.js, src/k8s/mock_templates/rhel-high-p.mock.js, src/k8s/mock_templates/rhel75.mock.js, src/k8s/mock_templates/ubuntu1804.mock.js, src/k8s/mock_templates/windows.mock.js, src/k8s/mock_user_templates/container-cloud.mock.js, src/k8s/mock_user_templates/container-multus.mock.js, src/k8s/mock_user_templates/container.mock.js, src/k8s/mock_user_templates/pxe-dv.mock.js, src/k8s/mock_user_templates/pxe-pvc.mock.js, src/k8s/mock_user_templates/pxe.mock.js, src/k8s/mock_user_templates/url-flavor.mock.js, src/k8s/mock_user_templates/url-nonetwork.mock.js, src/k8s/mock_user_templates/url.mock.js, src/k8s/mock_vm/cloudInitTestVm.mock.js, src/k8s/mock_vmi/blue.mock.js, src/k8s/mock_vmi/cloudInitTestVmi.mock.js, src/k8s/request.js, src/k8s/request/tests/__snapshots__/cloudInit.test.js.snap, src/k8s/tests/request.test.js, src/models/index.js, src/utils/selectors.js, src/utils/templates.js, src/utils/tests/utils.test.js, src/utils/utils.js
https://github.com/kubevirt/kubevirt/pull/1570
=> volumeName from disk spec is removed. apiVersion changed to v1alpha3.

src/components/CreateNicRow/CreateNicRow.js, src/components/CreateNicRow/tests/__snapshots__/CreateNicRow.test.js.snap, src/components/Wizard/CreateVmWizard/NetworksTab.js, src/components/Wizard/CreateVmWizard/StorageTab.js, src/components/Wizard/CreateVmWizard/strings.js, src/components/Wizard/CreateVmWizard/tests/__snapshots__/NetworksTab.test.js.snap, src/components/Wizard/CreateVmWizard/tests/__snapshots__/StorageTab.test.js.snap
https://github.com/kubevirt/web-ui-components/issues/103
=> Rename NIC/Disk Name to just Name

src/utils/utils.js
Move getResource() to web-ui-components from the web-ui.
=> Refactor: move getResource() to web-ui-components

src/k8s/mock_templates/fedora28.mock.js, src/k8s/mock_templates/rhel-high-p.mock.js, src/k8s/mock_templates/rhel75.mock.js, src/k8s/mock_templates/ubuntu1804.mock.js, src/k8s/mock_templates/windows.mock.js, src/k8s/tests/request.test.js, src/models/index.js, src/utils/tests/templates.test.js, src/utils/utils.js
Use ProjectModel instead of NamespaceModel when requesting resources.
=> Move mocked templates to openshift namespace.

src/components/Details/VmDetails/fixtures/VmDetails.fixture.js, src/constants/index.js, src/k8s/request.js, src/k8s/tests/request.test.js, src/tests/mocks/user_template/container-cloud.mock.js, src/tests/mocks/user_template/container-multus.mock.js, src/tests/mocks/user_template/container.mock.js, src/tests/mocks/user_template/pxe-dv.mock.js, src/tests/mocks/user_template/pxe-pvc.mock.js, src/tests/mocks/user_template/pxe.mock.js, src/tests/mocks/user_template/url-flavor.mock.js, src/tests/mocks/user_template/url-nonetwork.mock.js, src/tests/mocks/user_template/url.mock.js, src/utils/selectors.js, src/utils/tests/templates.test.js
https://github.com/kubevirt/web-ui/issues/133
=> Add template name and namespace to VM labels.

src/components/Form/Dropdown.js
Useful when content is retrieved asynchronously.
Will be needed for V2V.
=> Dropdown: choices are optional

src/models/index.js
=> Add SecretsModel

src/components/Wizard/CreateVmWizard/StorageTab.js
For stability of other flows.
Issue found when implementing v2v.
=> StorageTab: fix for empty list

src/models/index.js
Copy&paste from web-ui.
For V2V
=> models: Add ServiceModel and RouteModel

sass/_components.scss, sass/components/Form/dropdown.scss, sass/patternfly-tweaks/dropdown.scss, src/components/Form/Dropdown.js, src/components/Form/fixtures/Dropdown.fixture.js, src/components/Form/tests/Dropdown.test.js, src/components/Form/tests/__snapshots__/Dropdown.test.js.snap, src/components/Form/tests/__snapshots__/FormFactory.test.js.snap
The content of dropdown button menu items are shortened if needed
=> Dropdown: overflow for long values

src/components/Wizard/CreateVmWizard/providers/VCenterVmsWithPrefill.js, src/components/Wizard/CreateVmWizard/providers/tests/VCenterVmsWithPrefill.test.js
Contains:
- refactoring of the VCenterVmsWithPrefill to simplify unit testing and share code
- prefil of CPU and Memory using `Custom` flavor
=> v2v: prefill cpu and memory

src/components/Wizard/CreateVmWizard/providers/VCenterVmsWithPrefill.js, src/components/Wizard/CreateVmWizard/providers/tests/VCenterVmsWithPrefill.test.js
=> v2v: add more unit tests

src/components/Wizard/CreateVmWizard/BasicSettingsTab.js, src/components/Wizard/CreateVmWizard/CreateVmWizard.js, src/components/Wizard/CreateVmWizard/NetworksTab.js, src/components/Wizard/CreateVmWizard/StorageTab.js, src/components/Wizard/CreateVmWizard/constants.js, src/components/Wizard/CreateVmWizard/providers/VCenterVmsWithPrefill.js, src/components/Wizard/CreateVmWizard/providers/tests/VCenterVmsWithPrefill.test.js, src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js
The Storage tab of the Create VM Wizard is populated by VMWare VM disks
during import.
=> v2v: prefill disks

src/utils/status/vm/vmStatus.js
=> Fix export of status functions

src/components/CreateDeviceRow/CreateDeviceRow.js, src/components/CreateDeviceRow/tests/__snapshots__/CreateDeviceRow.test.js.snap, src/components/Dialog/CloneDialog/tests/__snapshots__/CloneDialog.test.js.snap, src/components/Form/FormFactory.js, src/components/Form/tests/__snapshots__/FormFactory.test.js.snap, src/components/VmConsoles/tests/__snapshots__/DesktopViewerSelector.test.js.snap, src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap, src/components/Wizard/CreateVmWizard/tests/__snapshots__/NetworksTab.test.js.snap, src/components/Wizard/CreateVmWizard/tests/__snapshots__/StorageTab.test.js.snap
Broken by #274 see my comment https://github.com/kubevirt/web-ui-components/pull/274#issuecomment-474305129
=> Ability to specify if form field labels should be shown

src/components/ClusterOverview/Utilization/Utilization.js, src/components/ClusterOverview/Utilization/fixtures/Utilization.fixture.js, src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap, src/selectors/prometheus/selectors.js
=> ClusterOverview: Add Memory to Utilization 

src/components/ClusterOverview/Capacity/Capacity.js, src/components/ClusterOverview/Capacity/fixtures/Capacity.fixture.js, src/components/ClusterOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap, src/utils/utils.js
=> ClusterOverview: Improve prometheus query for CPU Capacity

src/components/ClusterOverview/Capacity/Capacity.js, src/components/ClusterOverview/Capacity/fixtures/Capacity.fixture.js, src/components/ClusterOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap, src/selectors/prometheus/selectors.js
To decrease count of Prometheus requests.
=> ClusterOverview: Merge CPU/mem Capacity and Utilization stats

src/components/StorageOverview/StorageOverview.js, src/components/StorageOverview/Utilization/Utilization.js, src/components/StorageOverview/Utilization/fixtures/Utilization.fixture.js, src/components/StorageOverview/Utilization/tests/Utilization.test.js, src/components/StorageOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap, src/components/StorageOverview/fixtures/StorageOverview.fixture.js, src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
ref: https://github.com/kubevirt/web-ui/pull/281
=> Added Performace/Utilization card

sass/components/Dashboard/events.scss, src/components/ClusterOverview/Events/Events.js, src/components/ClusterOverview/Events/tests/__snapshots__/Events.test.js.snap, src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap, src/components/StorageOverview/Events/Events.js, src/components/StorageOverview/Events/tests/__snapshots__/Events.test.js.snap, src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
@cloudbehl followup for https://github.com/kubevirt/web-ui-components/pull/324
=> Fix css for events dashboard card

src/components/Dashboard/Inventory/utils.js
=> [Cluster dashboard] Indicate when hosts are in progress

sass/_components.scss, sass/components/StorageOverview/data-resiliency.scss, src/components/StorageOverview/DataResiliency/DataResiliency.js, src/components/StorageOverview/DataResiliency/fixtures/DataResiliency.fixture.js, src/components/StorageOverview/DataResiliency/tests/DataResiliency.test.js, src/components/StorageOverview/DataResiliency/tests/__snapshots__/DataResiliency.test.js.snap, src/components/StorageOverview/StorageOverview.js, src/components/StorageOverview/fixtures/StorageOverview.fixture.js
-fixtures ans tests for it
-component
[kubevirt/web-ui/pull/276](https://github.com/kubevirt/web-ui/pull/276)
=> Added data resiliency card

package.json
- Utilization: Add Disk Usage chart (#322)
- Fix css for events dashboard card (#336)
- Align byte units to tectonic ones. (#338)
- Typo changes to storage dashboard (#344)
- Do not map vm status off to status ok (#340)
- Pass LoadingComponent to inventory rows (#345)
- remove rhhi version (#347)
- Add Host Status selector and components (#293)
- Add BaremetalHostRole component (#339)
- Add utility to check if host can add machine (#333)
- Add default host status when host does not have status data (#350)
- Rename cnv.io labels to kubevirt.io (#331)
- Add progress indicator for hosts in cluster dashboard (#335)
=> Bump 0.1.27

src/components/ClusterOverview/Inventory/Inventory.js, src/components/ClusterOverview/Inventory/tests/__snapshots__/Inventory.test.js.snap, src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap, src/components/Dashboard/Inventory/utils.js, src/constants/index.js, src/constants/storage.js
=> [Cluster overview] Add disks to inventory

sass/components/Dashboard/utilization.scss, src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap, src/components/Dashboard/Utilization/UtilizationItem.js, src/components/Dashboard/Utilization/tests/__snapshots__/UtilizationBody.test.js.snap, src/components/Dashboard/Utilization/tests/__snapshots__/UtilizationItem.test.js.snap, src/components/StorageOverview/Utilization/Utilization.js, src/components/StorageOverview/Utilization/fixtures/Utilization.fixture.js, src/components/StorageOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap, src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
ref: https://github.com/kubevirt/web-ui/pull/306
=> Changed the order of charts, added recovery chart in performance card

src/components/Dashboard/Health/HealthItem.js, src/components/Dashboard/Health/tests/__snapshots__/HealthBody.test.js.snap, src/components/Dashboard/Health/tests/__snapshots__/HealthItem.test.js.snap, src/components/StorageOverview/OCSHealth/Health.js, src/components/StorageOverview/OCSHealth/tests/__snapshots__/Health.test.js.snap
1. Fixed health data path for real data (prometheus).
2. Fixed CSS changes in HealthItem wrt `kubevirt-health-...`
3. Changed Alignment of Health card.
4. Changed Loading Icon for health card in Storage Overview.
BEFORE-
AFTER-
=> Health Card Changes

src/components/BareMetalHosts/BaremetalHostRole.js, src/components/BareMetalHosts/fixtures/BaremetalHostRole.fixture.js, src/selectors/host/selectors.js, src/selectors/machine/fixtures/selectors.fixture.js, src/selectors/machine/index.js, src/selectors/machine/selectors.js, src/selectors/machine/tests/selectors.test.js
* rename getHostRole selector to getMachineRole
* move the getMachineRole to machine selectors
* fix the label to identify machine role
=> Update selector to get machine role

src/selectors/host/selectors.js
Ref: https://github.com/kubevirt/web-ui/pull/322
=> Introduce hardware host selectors

sass/_components.scss
Forgotten "git add". Proper fix is required.
=> Hotfix missing components/ClusterOverview/compliance

src/constants/index.js
https://bugzilla.redhat.com/show_bug.cgi?id=1702155
=> Remove whitespace from kubevirt.ui/firstBoot annotation

src/components/StorageOverview/TopConsumers/TopConsumers.js
Added 2 extra points on the Y-axis and increased domain such that no extra space is seen.
=> Change to y axis of Top Projects card

src/components/ClusterOverview/Health/Health.js, src/components/ClusterOverview/Health/tests/__snapshots__/Health.test.js.snap
backport of https://github.com/kubevirt/web-ui-components/pull/413
=> Fix dashboard health typo - degrated/degraded

src/components/Wizard/CreateVmWizard/providers/VCenterInstances.js, src/components/Wizard/CreateVmWizard/providers/VCenterVms.js, src/config/index.js, src/k8s/objects/v2v/vmware/conversionPod.js, src/k8s/objects/v2v/vmware/vmWareDeployment.js
- sort vms
- show duplicate vms only once
=> v2v: fix connecting to new instance & enhance

sass/components/Wizard/create-vm-wizard.scss, src/components/VmConsoles/tests/__snapshots__/DesktopViewerSelector.test.js.snap, src/components/Wizard/CreateVmWizard/CreateVmWizard.js, src/components/Wizard/CreateVmWizard/ResultTabRow.js, src/components/Wizard/CreateVmWizard/fixtures/ResultTabRow.fixture.js, src/components/Wizard/CreateVmWizard/strings.js, src/components/Wizard/CreateVmWizard/tests/__snapshots__/ResultTabRow.test.js.snap, src/k8s/request.js, src/k8s/requests/v2v/importVmware.js, src/k8s/selectors.js, src/k8s/tests/request.test.js, src/k8s/util/enhancedK8sMethods.js, src/k8s/util/errors.js, src/k8s/util/index.js, src/k8s/util/tests/enhancedK8sMethods.test.js, src/k8s/util/utils.js, src/tests/mocks/vm/vm.mock.js, src/utils/utils.js
- rollback already created objects when the request fails
- change results history approach
- enhance resultsTab
=>  enhance k8s methods

yarn.lock
=> revert yarn.lock

src/components/ClusterOverview/TopConsumers/TopConsumers.js, src/components/ClusterOverview/TopConsumers/strings.js, src/components/ClusterOverview/TopConsumers/tests/__snapshots__/TopConsumers.test.js.snap, src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap
We want to update the top consumers data collected in web-ui, this PR update the description and units to match this cahnges.
Depends on kubevirt/web-ui#351
Ref:
https://jira.coreos.com/browse/CNV-1157
=> Update top consumers description and units

src/components/CreateBaremetalHostDialog/CreateBaremetalHostDialog.js, src/components/CreateBaremetalHostDialog/tests/__snapshots__/CreateBaremetalHostDialog.test.js.snap, src/constants/index.js, src/utils/strings.js, src/utils/tests/validation.test.js, src/utils/validations.js
Validate the controller address in the create a new baremetal host dialog
=> Add a controller address validation

src/components/VmStatus/VmStatus.js, src/components/VmStatus/tests/__snapshots__/VmStatus.test.js.snap
Update string to match BZ.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1701724
=> Update string conversion to import (vmware)

src/components/VmStatus/VmStatus.js, src/components/VmStatus/tests/__snapshots__/VmStatus.test.js.snap
Update string to match BZ.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1701724
Backport of: https://github.com/kubevirt/web-ui-components/pull/447/
=> [web-ui-v2.0.0] Update string conversion to import (vmware)

src/components/Wizard/CreateVmWizard/CreateVmWizard.js, src/components/Wizard/CreateVmWizard/constants.js, src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js, src/components/Wizard/CreateVmWizard/validations/utils.js, src/components/Wizard/CreateVmWizard/validations/validators.js, src/components/Wizard/CreateVmWizard/validations/vmSettingsTabValidation.js, src/tests/mocks/vm/vm_validation.mock.js, src/utils/strings.js, src/utils/tests/validation.test.js, src/utils/validations.js
This PR adds a validation check to ensure that a duplicate VM name is not provided.
Bug: https://bugzilla.redhat.com/1697333
Depends on: https://github.com/kubevirt/web-ui/pull/367
=> Display error on duplicate VM name in wizard

src/components/StorageOverview/Alerts/tests/Alerts.test.js, src/components/StorageOverview/Events/Events.js, src/components/StorageOverview/Events/fixtures/Events.fixture.js, src/components/StorageOverview/Events/tests/Events.test.js, src/components/StorageOverview/Events/tests/__snapshots__/Events.test.js.snap, src/components/StorageOverview/Inventory/Inventory.js, src/components/StorageOverview/Inventory/fixtures/Inventory.fixture.js, src/components/StorageOverview/Inventory/tests/__snapshots__/Inventory.test.js.snap, src/components/StorageOverview/OCSHealth/Health.js, src/components/StorageOverview/OCSHealth/fixtures/Health.fixture.js, src/components/StorageOverview/OCSHealth/tests/__snapshots__/Health.test.js.snap, src/components/StorageOverview/StorageOverviewContext/StorageOverviewContext.js, src/components/StorageOverview/StorageOverviewContext/index.js, src/components/StorageOverview/TopConsumers/TopConsumers.js, src/components/StorageOverview/TopConsumers/fixtures/TopConsumers.fixture.js, src/components/StorageOverview/TopConsumers/tests/TopConsumers.test.js, src/components/StorageOverview/TopConsumers/tests/__snapshots__/TopConsumers.test.js.snap, src/components/StorageOverview/fixtures/StorageOverview.fixture.js
Use StorageOverviewContext.Consumer everywhere.
web-ui PR https://github.com/kubevirt/web-ui/pull/361
=> Refactor storage cards to use new props format.

src/components/Details/VmDetails/VmDetails.js, src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap, src/k8s/request.js, src/selectors/vmi/selectors.js
backport of https://github.com/kubevirt/web-ui-components/pull/392
=> Correct hostname display in VM overview tab

src/components/Details/VmDetails/VmDetails.js, src/components/Details/VmTemplateDetails/VmTemplateDetails.js
- forbid state updates on unmounted component
@rhrazdil this should prevent the known console.err of VmTemplateDetails
=> make details components safe for async requests

sass/_components.scss, sass/components/Dashboard/dashboard.scss, sass/components/Dashboard/dropdown.scss, src/components/Dashboard/DashboardCard/DashboardCardActionsBody.js, src/components/Dashboard/DashboardCard/fixtures/DashboardCardActionsBody.fixture.js, src/components/Dashboard/DashboardCard/tests/DashboardCardActionsBody.test.js, src/components/Dashboard/DashboardCard/tests/__snapshots__/DashboardCardActionsBody.test.js.snap, src/components/Form/Dropdown.js, src/components/Form/FormFactory.js, src/components/Form/tests/__snapshots__/FormFactory.test.js.snap, src/components/StorageOverview/TopConsumers/TopConsumers.js, src/components/StorageOverview/TopConsumers/fixtures/TopConsumers.fixture.js, src/components/StorageOverview/TopConsumers/strings.js, src/components/StorageOverview/TopConsumers/tests/TopConsumers.test.js, src/components/StorageOverview/TopConsumers/tests/__snapshots__/TopConsumers.test.js.snap, src/components/StorageOverview/fixtures/StorageOverview.fixture.js, src/selectors/prometheus/storage.js
ref: https://github.com/kubevirt/web-ui/pull/370
After adding the dropdowns to top consumer card, it looks like this  -
=> Created dropdown component and integrated it with top consumer card

src/components/Dialog/CloneDialog/CloneDialog.js, src/utils/validations.js
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1711136
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1711858
=> Fix import of validateVmName()

src/components/Wizard/CreateVmWizard/NetworksTab.js, src/components/Wizard/CreateVmWizard/strings.js
https://bugzilla.redhat.com/show_bug.cgi?id=1710914
=> Improve empty network name message

src/components/Dashboard/strings.js, src/components/StorageOverview/Alerts/Alerts.js, src/components/StorageOverview/Alerts/tests/Alerts.test.js, src/components/StorageOverview/Alerts/tests/__snapshots__/Alerts.test.js.snap
Added dropddown which filters the alerts as per the severity: All, Critical, and Warning.
=> Added dropdown for alerts card in storage dashboard

src/components/Wizard/CreateVmWizard/CreateVmWizard.js, src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap
backport of https://github.com/kubevirt/web-ui-components/pull/471
https://bugzilla.redhat.com/show_bug.cgi?id=1710888
=> Do not close Create VM Wizard when clicked outside of modal

src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap, src/components/Wizard/CreateVmWizard/validations/vmSettingsTabValidation.js, src/utils/validations.js
https://bugzilla.redhat.com/show_bug.cgi?id=1710775
we should allow floats and different values than Gi for web-ui future versions
=> Do not allow floats as memory value

src/components/Wizard/CreateVmWizard/stateUpdate/providers/vmWareStateUpdate.js
- BZ https://bugzilla.redhat.com/show_bug.cgi?id=1710944
=> CreateVmWizard WMware - fix: fields become inactive after the VM is picked

src/k8s/migrate.js, src/k8s/tests/migrate.test.js, src/tests/k8s.js
https://bugzilla.redhat.com/show_bug.cgi?id=1715050
=> Use k8s generateName for migration objects

src/components/ClusterOverview/Inventory/tests/__snapshots__/Inventory.test.js.snap, src/components/VmConsoles/tests/__snapshots__/DesktopViewerSelector.test.js.snap, src/constants/index.js, src/k8s/objects/pvc/pvc.js, src/k8s/vmBuilder.js, src/tests/mocks/dataVolume/index.js, src/tests/mocks/user_template/pvc.mock.js, src/tests/mocks/user_template/pxe-dv.mock.js, src/tests/mocks/user_template/url-flavor.mock.js, src/tests/mocks/user_template/url-nonetwork.mock.js, src/tests/mocks/user_template/url.mock.js, src/tests/mocks/vm/vm.mock.js, src/tests/mocks/vm/vm_validation.mock.js, src/utils/patches.js, src/utils/tests/patches.test.js
https://bugzilla.redhat.com/show_bug.cgi?id=1719134
=> Change PVC access mode to RWM

src/components/StorageOverview/TopConsumers/TopConsumers.js, src/components/StorageOverview/TopConsumers/strings.js, src/components/StorageOverview/TopConsumers/tests/TopConsumers.test.js, src/components/StorageOverview/TopConsumers/tests/__snapshots__/TopConsumers.test.js.snap, src/selectors/prometheus/storage.js
=> added dropdown for VMs in top consumers card

src/components/Wizard/CreateVmWizard/CreateVmWizard.js, src/components/Wizard/CreateVmWizard/initialState/providers/vmWareInitialState.js, src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/VMWareImportProvider.js, src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/constants.js, src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/requestedResources.js, src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/tests/__snapshots__/VMWareImportProvider.test.js.snap, src/components/Wizard/CreateVmWizard/stateUpdate/providers/vmWareStateUpdate.js, src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap, src/k8s/requests/v2v/correctVCenterSecretLabels.js
- optimization and small refactoring
sibling: https://github.com/kubevirt/web-ui/pull/412
=> V2V: Listen on active VCenter Secret only when import provider is active

src/components/Wizard/CreateVmWizard/CreateVmWizard.js, src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/VMWareImportProvider.js, src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/requestedResources.js, src/k8s/util/k8sMethodsUtils.js
=> CreateVmDialog uses Firehose

yarn.lock
=> Upgrade lodash to 4.17.14

yarn.lock
Due to security vulnerabilities.
=> Upgrade js-yaml and lodash

src/components/Dialog/CloneDialog/CloneDialog.js, src/components/Wizard/CreateVmWizard/constants.js, src/components/Wizard/CreateVmWizard/validations/vmSettingsTabValidation.js, src/utils/strings.js, src/utils/tests/validation.test.js, src/utils/validations.js
bz: https://bugzilla.redhat.com/show_bug.cgi?id=1717802
=> fix VM Template name validation

src/components/Wizard/CreateVmWizard/initialState/providers/vmWareInitialState.js, src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/tests/__snapshots__/VMWareImportProvider.test.js.snap, src/components/Wizard/CreateVmWizard/strings.js
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1724961
---
=> v2v: change "VM to import" to "VM or Template"

src/k8s/requests/v2v/tests/utils.test.js, src/k8s/requests/v2v/utils.js
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1710897
=> v2v: generate shorter vCenter instance secret name

src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/VMWareImportProvider.js, src/components/Wizard/CreateVmWizard/validations/providers/vmWareValidation.js
=> v2v: fix VM loading when race condition occurs

src/components/Wizard/CreateVmWizard/NetworksTab.js, src/components/Wizard/CreateVmWizard/strings.js, src/components/Wizard/CreateVmWizard/tests/NetworksTab.test.js, src/utils/strings.js, src/utils/tests/validation.test.js, src/utils/validations.js
Bug: https://bugzilla.redhat.com/1720333
=> Add MAC address validation to Create VM wizard

package.json
Follow up to #536. Forgot the reference for Webpack.
Edit: Also, please publish this to NPM!
=> Add module to package.json

src/components/Wizard/CreateVmWizard/fixtures/CreateVmWizard.fixture.js, src/components/Wizard/CreateVmWizard/validations/utils.js, src/utils/grammar.js
https://bugzilla.redhat.com/show_bug.cgi?id=1727056
Edit: https://bugzilla.redhat.com/show_bug.cgi?id=1743938
=> kubevirt: fix addMissingSubject

src/k8s/requests/v2v/importVmware.js
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1756328
=> Always use RWO accessMode for conversion pod temporary disk

src/k8s/requests/v2v/importVmware.js
Backport of: #561 
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1756328
Depends on: #565
=> Backport 561, BZ 1756328:

package.json
Signed-off-by: Marek Libra <marek.libra@gmail.com>
=> Bump 0.1.44.1

src/k8s/objects/v2v/vmware/conversionPod.js, src/k8s/requests/v2v/importVmware.js, src/selectors/pod/combined.js
=> v2v: add VM name to the conversion pod name

package.json
Signed-off-by: Marek Libra <marek.libra@gmail.com>
=> Bump 0.1.49

config/babel.config.js, package.json, yarn.lock
=> fix(plugins): add spread operator plugin for edge support (#572)

package.json
Signed-off-by: Marek Libra <marek.libra@gmail.com>
=> Bump 0.1.44-2

package.json
Signed-off-by: Marek Libra <marek.libra@gmail.com>
=> Bump 0.1.50
