kubevirt/web-ui-components

.eslintrc.js, .prettierrc, .stylelintrc, package.json, src/components/App.css, src/components/App.js, src/components/Button.stories.js, yarn.lock
JS linting is based on the patternfly-react eslint package
I also added an npm package for storybook deployer so we can easily share PR reviews.
This include fixing all the linting errors as well :)
=> Add JS and CSS linting support

.travis.yml
Linter is not executed explicitely by travis since it is farther
included in a more generic `yarn dist` target.
The `yarn test` remains since it is required to collect coveralls data.
=> Travis: remove linter

package.json
With this fix, the consuming project can simply
```
import ... from "kubevirt-web-ui-components"
```
indested of
```
import ... from "kubevirt-web-ui-components/dist/js"
```
=> Fix "main" JS entry

tools/travis/tasks/exportCosmos.js
This fixes the problem of [GitHub Pages not serving files that start with an underscore](https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/).
=> Turn off Jekyll when served via GitHub Pages

src/components/Wizard/NewVmWizard/fixtures/NewVmWizard.fixture.js
I am not sure if this component is still needed, because it is not used in kubevirt/we-ui? Maybe we should deprecate it.
=> NewVmWizard: fix fixture

config/jest.config.js, package.json, sass/_components.scss, sass/components/_VmConsoles.scss, src/components/VmConsoles/SerialConsoleConnector.js, src/components/VmConsoles/VmConsoles.js, src/components/VmConsoles/fixtures/SerialConsoleConnector.fixture.js, src/components/VmConsoles/fixtures/VmConsoles.fixture.js, src/components/VmConsoles/index.js, src/components/VmConsoles/tests/SerialConsoleConnector.test.js, src/components/VmConsoles/tests/VmConsoles.test.js, src/components/VmConsoles/tests/__snapshots__/SerialConsoleConnector.test.js.snap, src/components/VmConsoles/tests/__snapshots__/VmConsoles.test.js.snap, src/components/VmStatus/getVmStatus.js, src/index.js, src/jest/polyfills.js, src/jest/setupTest.js, yarn.lock
Based on `AccessConsoles` component from `paternfly/react-consoles` project.
=> Introduce VmConsoles component

src/components/VmConsoles/VmConsoles.js
This is a hotfix which will be handled in patternfly-react as well.
=> Fix VmConsoles: provide VncConsole type

src/components/VmStatus/VmStatus.js, src/components/VmStatus/fixtures/VmStatus.fixture.js, src/components/VmStatus/getVmStatus.js, src/components/VmStatus/tests/VmStatus.test.js, src/components/VmStatus/tests/__snapshots__/VmStatus.test.js.snap, src/constants/index.js
Happens after setting VM `running` but pod is not created yet.
Rendered as text value: Pending
Before this patch, the state was VM_STATUS_UNKNOWN in this case.
=> Introduce VM_STATUS_VMI_WAITING state

src/components/VmStatus/fixtures/VmStatus.fixture.js, src/components/VmStatus/getVmStatus.js
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1661870
was not tried in real environment but should be correct according to https://github.com/kubevirt/kubevirt/blob/master/pkg/api/v1/types.go
=> fix isBeingMigrated function

sass/components/_VmConsoles.scss, src/components/VmConsoles/VmConsoles.js, src/components/VmConsoles/fixtures/VmConsoles.fixture.js, src/components/VmConsoles/tests/VmConsoles.test.js, src/components/VmConsoles/tests/__snapshots__/VmConsoles.test.js.snap, src/constants/index.js, src/k8s/request.js, src/utils/selectors.js
With this patch the DesktopViewer is added among other console types.
TODO:
=> Add DesktopViewer to VmConsoles

sass/components/VmDetails/vm-details.scss, src/components/Details/VmDetails/VmDetails.js, src/components/Details/VmDetails/fixtures/VmDetails.fixture.js, src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap
@andybraren This is how edit VM details currently looks like
I know that in the desing you have edit button as a part of Actions dropdown but this is currently not possible
I need to disable editing if VM is running and I would like to let the user know why. Is this solution ok ?
Editing in progress
=> Disable VM editing if VM is running

src/components/VmConsoles/VmConsoles.js, src/components/VmConsoles/tests/__snapshots__/VmConsoles.test.js.snap
This helps to prevent failures when reconnecting.
**Partial** workaround for https://github.com/kubevirt/kubevirt/issues/1893
=> VmConsoles: Connection is kept by default when switching console types

src/components/Details/VmDetails/VmDetails.js, src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap, src/utils/selectors.js
This PR fixes a bug [1] wherein the VMI isn't immediately deleted when the VM is shutdown, leading to the IP addresses still being displayed when the VM is in an off state. It also prevents the FQDN from being displayed if the pod isn't immediately deleted to avoid the potential of a similar issue occurring. 
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1665901.
=> Clear IP addresses & FQDN when VM is off

src/components/Details/VmDetails/VmDetails.js, src/components/Details/VmDetails/fixtures/VmDetails.fixture.js, src/components/Details/VmDetails/tests/VmDetails.test.js, src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap, src/utils/selectors.js, src/utils/tests/selectors.test.js
This PR addresses the following issues in the VM details dialog:
- Removes trailing comma when interfaces with missing/empty IP addresses are present
-- https://bugzilla.redhat.com/1668351
- Always displays dashes for the FQDN when the FQDN isn't available
=> Fix VM details issues

docs/DevGuide.md, src/components/VmStatus/VmStatus.js, src/components/VmStatus/tests/__snapshots__/VmStatus.test.js.snap
We need this for kubevirt/web-ui#189 - make element selectors within integration tests less dependent on rendered DOM structure.
cc @rhrazdil
=> Add BEM block to VmStatus component

src/components/Form/FormFactory.js
Custom component can be provided with custom props.
The onChange() event on a form component can be hooked for
additional (side-effect) actions, like triggering of external
action by selection in a dropdown.
=> FormFactory: pass extraProps to CustomComponent and onChange hook

src/components/Wizard/CreateVmWizard/CreateVmWizard.js
https://bugzilla.redhat.com/show_bug.cgi?id=1679488
=> prevent template rootdisk (the first bootable disk) from deletion when creating VMs

src/components/Details/Url/Url.js, src/components/Details/Url/fixtures/Url.fixture.js, src/components/Details/Url/index.js, src/components/Details/Url/tests/Url.test.js, src/components/Details/Url/tests/__snapshots__/Url.test.js.snap, src/components/Details/VmTemplateDetails/tests/__snapshots__/VmTemplateDetails.test.js.snap, src/components/TemplateSource/TemplateSource.js, src/components/TemplateSource/fixtures/TemplateSource.fixture.js, src/components/TemplateSource/tests/TemplateSource.test.js, src/components/TemplateSource/tests/__snapshots__/TemplateSource.test.js.snap, src/tests/mocks/user_template/url-flavor.mock.js, src/tests/mocks/user_template/url-nonetwork.mock.js, src/tests/mocks/user_template/url.mock.js, src/utils/tests/templates.test.js, src/utils/utils.js, src/utils/validations.js
Fixes #217 
Shortens url. The href and tooltip contain the original url.
base url: http://merlin.fit.vutbr.cz/mirrors/centos/7.6.1810/isos/x86_64/CentOS-7-x86_64-Minimal-1810.iso
base url: http://fit.vutbr.cz/mirrors/centos/7.6.1810/isos/x86_64/CentOS-7-x86_64-Minimal-1810.iso
base url: http://merlin.fit.vutbr.cz/CentOS-7-x86_64-Minimal-1810.iso?a=5#here
One disadvantage is that the elipsis can appear 3 times:  [...sub.hostname.end/.../final-part...]() 
The last bit for parameters. 
@andybraren What do you think?
=> shorten URL in VmTemplateDetail and refactor TemplateSource

sass/components/Wizard/create-vm-wizard.scss, src/components/Wizard/CreateVmWizard/CreateVmWizard.js, src/components/Wizard/CreateVmWizard/ResultTab.js, src/components/Wizard/CreateVmWizard/ResultTabRow.js, src/components/Wizard/CreateVmWizard/fixtures/ResultTab.fixture.js, src/components/Wizard/CreateVmWizard/fixtures/ResultTabRow.fixture.js, src/components/Wizard/CreateVmWizard/strings.js, src/components/Wizard/CreateVmWizard/tests/ResultTab.test.js, src/components/Wizard/CreateVmWizard/tests/ResultTabRow.test.js, src/components/Wizard/CreateVmWizard/tests/__snapshots__/ResultTab.test.js.snap, src/components/Wizard/CreateVmWizard/tests/__snapshots__/ResultTabRow.test.js.snap, src/k8s/request.js
implements RFE: https://bugzilla.redhat.com/show_bug.cgi?id=1667988
Successful creation:
Displays detail on click:
Failure (displays error by default):
Displays failed objects on click:
=> VmCreateDialog: display JSONs on error in ResultsTab

src/components/Form/FormFactory.js, src/components/Form/index.js, src/components/Wizard/CreateVmWizard/BasicSettingsTab.js, src/components/Wizard/CreateVmWizard/constants.js, src/components/Wizard/CreateVmWizard/providers/VCenterVms.js, src/components/Wizard/CreateVmWizard/providers/VCenterVmsWithPrefill.js, src/components/Wizard/CreateVmWizard/providers/fixtures/VCenterVmsWithPrefill.fixture.js, src/components/Wizard/CreateVmWizard/providers/tests/VCenterVms.test.js, src/components/Wizard/CreateVmWizard/providers/tests/VCenterVmsWithPrefill.test.js, src/components/Wizard/CreateVmWizard/providers/tests/__snapshots__/VCenterVmsWithPrefill.test.js.snap, src/components/Wizard/CreateVmWizard/providers/tests/vmwareActions.test.js, src/components/Wizard/CreateVmWizard/providers/vmwareActions.js, src/tests/k8s.js
If the user did not change the VM name or description fields within the CreateVmWizard, they are automatically pre-filled with the values from the imported VMWare VM.
To highlight:
- `FormFactory.getFormElement()` passes `onFormChange()` to a custom component. This slightly breaks encapsulation given by strictly context-bound `onChange()` but enables to build more complex flows in a custom component and so keeping business logic better co-located instead of spreading it to different layers (i.e. poluting BasicsettingsTab and CreateVmWizard components with inner-flow details).
- the `onFormChange()` handles `BATCH_CHANGES_KEY` so an array of `{ target, value }` pairs can be passed within a single call. We can consider this as a sort of "transaction". With existing design, it is not …
=> v2v: prefill Name and Description based on VMWare VM

src/components/Wizard/CreateVmWizard/BasicSettingsTab.js, src/components/Wizard/CreateVmWizard/CreateVmWizard.js, src/components/Wizard/CreateVmWizard/providers/VCenterVms.js, src/components/Wizard/CreateVmWizard/providers/vmwareActions.js, src/components/Wizard/CreateVmWizard/tests/BasicSettingsTab.test.js, src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap, src/k8s/selectors.js, src/tests/k8s.js
It is just a friendly help to keep things clean.
The garbage collector would remove these left-overs anyway but after a delay.
Thanks to this PR, the V2VVMWare are removed sooner.
=> v2v: Delete V2VVMWare object on CreateVmWizard close

sass/_components.scss, sass/components/VmDetails/boot-order.scss, src/components/Details/BootOrder/BootOrder.js, src/components/Details/BootOrder/fixtures/BootOrder.fixture.js, src/components/Details/BootOrder/index.js, src/components/Details/BootOrder/tests/BootOrder.test.js, src/components/Details/BootOrder/tests/__snapshots__/BootOrder.test.js.snap, src/components/Details/VmDetails/VmDetails.js, src/components/Details/VmDetails/fixtures/VmDetails.fixture.js, src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap, src/components/Details/VmTemplateDetails/VmTemplateDetails.js, src/components/Details/VmTemplateDetails/tests/__snapshots__/VmTemplateDetails.test.js.snap, src/constants/index.js, src/k8s/request.js, src/k8s/tests/request.test.js, src/k8s/vmBuilder.js, src/utils/patches.js, src/utils/tests/patches.test.js
This PR is to add a boot order component to the VM details dialog. Editing functionality will be added in a separate PR in the future.
Depends on: https://github.com/kubevirt/web-ui/pull/207
=> Add view-only boot order component to VM details dialog

src/components/Wizard/CreateVmWizard/BasicSettingsTab.js, src/components/Wizard/CreateVmWizard/providers/VCenterVms.js, src/components/Wizard/CreateVmWizard/providers/VCenterVmsWithPrefill.js, src/components/Wizard/CreateVmWizard/providers/index.js, src/components/Wizard/CreateVmWizard/providers/tests/VCenterVms.test.js, src/components/Wizard/CreateVmWizard/providers/tests/VCenterVmsWithPrefill.test.js, src/components/Wizard/CreateVmWizard/providers/tests/__snapshots__/VCenterVmsWithPrefill.test.js.snap, src/components/Wizard/CreateVmWizard/providers/vmware.js, src/components/Wizard/CreateVmWizard/providers/vmwareActions.js, src/components/Wizard/CreateVmWizard/strings.js, src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap, src/constants/index.js, src/models/index.js, src/tests/k8s.js, src/utils/utils.js
In CreateVMWizard and v2v flow, the operating system is prefilled
based on input value from the VMWare VM.
Mapping of vmware to kubevirt OS value is done via ConfigMap (single per cluster):
- name: vmware-to-kubevirt-os
- namespace: kube-public
Presence of the ConfigMap is not required.
---
TODO:
- https://github.com/kubevirt/web-ui-operator/pull/28
- https://github.com/kubevirt/kubevirt-ansible/pull/609
=> v2v: prefill operating system

src/components/Wizard/CreateVmWizard/BasicSettingsTab.js, src/components/Wizard/CreateVmWizard/CreateVmWizard.js, src/components/Wizard/CreateVmWizard/NetworksTab.js, src/components/Wizard/CreateVmWizard/constants.js, src/components/Wizard/CreateVmWizard/fixtures/NetworksTab.fixture.js, src/components/Wizard/CreateVmWizard/providers/VCenterVmsWithPrefill.js, src/components/Wizard/CreateVmWizard/providers/tests/VCenterVmsWithPrefill.test.js, src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js
The `Networks` tab of the Create VM Wizard is filled by networks of the imported VMWare VM.
The user is expected to pair source networks with the target network configurations.
=> v2v: prefill networks

src/components/Details/Url/Url.js, src/components/Details/Url/tests/__snapshots__/Url.test.js.snap, src/components/Details/VmTemplateDetails/tests/__snapshots__/VmTemplateDetails.test.js.snap
this PR removes the parameters and hash part 
moving conversation from #229 to here:
@andybraren
> Ah you’re right, I agree that hinting at additional subdomains is important and the “...” should be kept in that case.
>
> Are protocols other than http/https (ftp/sftp/smb) supported? If yes then the protocol is probably important enough to show at all times, despite the increased length. If no then I would still lean toward being able to hide http/https entirely without a “...”, but I defer to your judgment in this context.
>
> So my proposal:
>
> https://...sub.domain.com/filename.iso (additional subdomains stripped, but protocol is kept because we decide it’s important)
>
> sub.domain.com/.../filename.iso (we decide the protocol is not important)
>
> ...sub.domain.com/.../filename.iso …
=> Details: remove search&hash elipsization

src/index.js, src/models/index.js, src/utils/selectors.js
This pull request adds BaremetalHostModel definition to models, introduces basic getHostStatus selector to be used with hosts filtering and determining host status.
=> Host status selector

src/components/Wizard/CreateVmWizard/CreateVmWizard.js
Hot fix only.
The PVC should be enough but recent validation within UI expects the PVC to be already
created if used in the StorageTab of the Create VM Wizard.
The v2v flow will create the PVC during final step of the wizard, right before
creating the Conversion POD.
=> v2v: use datavolume instead of PVC

package.json, src/components/Details/Url/tests/Url.test.js, src/components/Form/FormFactory.js, src/components/TemplateSource/tests/TemplateSource.test.js, src/components/VmStatus/VmStatus.js, src/components/Wizard/CreateVmWizard/NetworksTab.js, src/components/Wizard/CreateVmWizard/StorageTab.js, src/components/Wizard/CreateVmWizard/tests/NetworksTab.test.js, src/components/Wizard/CreateVmWizard/tests/ResultTab.test.js, src/components/Wizard/CreateVmWizard/tests/ResultTabRow.test.js, src/components/Wizard/CreateVmWizard/tests/StorageTab.test.js, src/components/Wizard/loadingWizardTab.js, src/cosmos/enzyme.js, src/k8s/clone.js, src/utils/templates.js, yarn.lock
Dependencies are upgraded within limits set in the package.json (untouched).
Needs to be verified manually.
=> Upgrade yarn.lock

sass/components/ClusterOverview/detail.scss, src/components/ClusterOverview/ClusterOverview.js, src/components/ClusterOverview/Details/ClusterDetails.js, src/components/ClusterOverview/Details/Details.js, src/components/ClusterOverview/Details/fixtures/ClusterDetails.fixture.js, src/components/ClusterOverview/Details/fixtures/Details.fixture.js, src/components/ClusterOverview/Details/tests/ClusterDetails.test.js, src/components/ClusterOverview/Details/tests/Details.test.js, src/components/ClusterOverview/Details/tests/__snapshots__/ClusterDetails.test.js.snap, src/components/ClusterOverview/fixtures/ClusterOverview.fixture.js, src/components/ClusterOverview/index.js, src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap, src/components/Loading/Loading.js, src/components/Loading/index.js
Create Cluster Details Card
Add loading state to Details item
=> Create Cluster Details Card

src/utils/status/vm/vmStatus.js
reverts #279 
I do not think it is necessary to export function which are not needed anywhere else.
the build was broken because #264 was merged but the sibling PR https://github.com/kubevirt/web-ui/pull/224 was not.
The API was changed a bit with these changes and `isMigrating` function was extracted to selectors. I think similar on spot functionality like `isMigrating` can be resolved with selectors and is not necessary to wrap it in status object. We can export these functions once the need arises.
=> do not export unnecessary functions

src/cosmos/proxies.js
Use empty array default proxy list.
Without this fix, cosmos 4.7 fails to load.
=> Fix cosmos

src/components/Dialog/CloneDialog/tests/__snapshots__/CloneDialog.test.js.snap, src/components/Form/FormFactory.js, src/components/Form/tests/__snapshots__/FormFactory.test.js.snap, src/components/VmConsoles/tests/__snapshots__/DesktopViewerSelector.test.js.snap, src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap, src/components/Wizard/CreateVmWizard/tests/__snapshots__/NetworksTab.test.js.snap, src/components/Wizard/CreateVmWizard/tests/__snapshots__/StorageTab.test.js.snap
When the form is vertical, we simply use the `<ControlLabel>` component to display the label.  When it's horizontal, we wrap the simple `<ControlLabel>` component in a `<Col>` --- just like it was done before.
This retains the previous functionality of horizontal forms.
=> Create labels for elements in vertical forms

sass/_components.scss, sass/components/CreateBaremetalHostDialog/create-baremetal-host-dialog.scss, src/components/CreateBaremetalHostDialog/CreateBaremetalHostDialog.js, src/components/CreateBaremetalHostDialog/fixtures/CreateBaremetalHostDialog.fixture.js, src/components/CreateBaremetalHostDialog/index.js, src/components/CreateBaremetalHostDialog/strings.js, src/components/CreateBaremetalHostDialog/tests/CreateBaremetalHostDialog.test.js, src/components/CreateBaremetalHostDialog/tests/__snapshots__/CreateBaremetalHostDialog.test.js.snap, src/components/Loading/Loading.js, src/index.js, src/k8s/request.js, src/k8s/requests/hosts/index.js
cc @knowncitizen @jtomasek @flofuchs
=> Add a component for creating baremetal hosts

sass/_components.scss, sass/components/Flavor/flavor.scss, src/components/Details/Description/tests/__snapshots__/Description.test.js.snap, src/components/Details/Flavor/Flavor.js, src/components/Details/Flavor/fixtures/Flavor.fixture.js, src/components/Details/Flavor/tests/Flavor.test.js, src/components/Details/Flavor/tests/__snapshots__/Flavor.test.js.snap, src/components/Details/VmDetails/VmDetails.js, src/components/Details/VmDetails/fixtures/VmDetails.fixture.js, src/components/Details/VmDetails/tests/VmDetails.test.js, src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap, src/components/Details/VmTemplateDetails/VmTemplateDetails.js, src/components/Details/VmTemplateDetails/fixtures/VmTemplateDetails.fixture.js, src/components/Details/VmTemplateDetails/tests/VmTemplateDetails.test.js, src/components/Details/VmTemplateDetails/tests/__snapshots__/VmTemplateDetails.test.js.snap, src/components/InlineEdit/InlineEdit.js, src/selectors/vm/selectors.js, src/tests/mocks/user_template/container-cloud.mock.js, src/tests/mocks/user_template/index.js
**Description**
When we want to render VmDetails with missing VmTemplate we get a warning that we can not find the template. But It is OK to delete a template of an existing vm, the view should silently fall back to vm's current resources.
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1685393
**Screenshots**
When template is missing, show warning triangle instead of an error:
Replace drop-down with a label when only one flavor option is available:
Add an optional template resource link method to vmDetails:
Show labels for CPU and Memory in flavor form:
=> Render VmDetails with deleted template curreclty.

src/utils/status/vm/vmStatus.js
This PR changes the ordering of VM statuses in vmStatus to check importing status before running status to avoid the VM reflecting a status of "Off" when it is actually in "Importing" status.
=> Fix vmStatus ordering

sass/_components.scss, sass/components/ClusterOverview/utilization.scss, sass/components/Dashboard/utilization.scss, src/components/ClusterOverview/ClusterOverview.js, src/components/ClusterOverview/Utilization/Utilization.js, src/components/ClusterOverview/Utilization/fixtures/Utilization.fixture.js, src/components/ClusterOverview/Utilization/tests/Utilization.test.js, src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap, src/components/ClusterOverview/fixtures/ClusterOverview.fixture.js, src/components/ClusterOverview/index.js, src/components/Dashboard/Capacity/CapacityItem.js, src/components/Dashboard/Utilization/UtilizationBody.js, src/components/Dashboard/Utilization/UtilizationItem.js, src/components/Dashboard/Utilization/fixtures/UtilizationBody.fixture.js, src/components/Dashboard/Utilization/fixtures/UtilizationItem.fixture.js, src/components/Dashboard/Utilization/strings.js, src/components/Dashboard/Utilization/tests/UtilizationBody.test.js, src/components/Dashboard/Utilization/tests/UtilizationItem.test.js, src/components/Dashboard/Utilization/tests/__snapshots__/UtilizationBody.test.js.snap, src/components/Dashboard/Utilization/tests/__snapshots__/UtilizationItem.test.js.snap, src/selectors/prometheus/selectors.js
Utilization card is refactored to split concern between
ClusterOverview and Dashboard components.
Connected to real data.
So far CPU only, other items will follow.
=> ClusterOverview: refactor Utilization card and connect

package.json, sass/components/Dashboard/utilization.scss, src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap, src/components/Dashboard/Utilization/UtilizationItem.js, src/components/Dashboard/Utilization/tests/UtilizationBody.test.js, src/components/Dashboard/Utilization/tests/UtilizationItem.test.js, src/components/Dashboard/Utilization/tests/__snapshots__/UtilizationBody.test.js.snap, src/components/Dashboard/Utilization/tests/__snapshots__/UtilizationItem.test.js.snap, yarn.lock
The Utilization component renders different sub-component structure
for a narrow container.
=> Dashboard, Utilization: Render in narrow container

src/components/CreateNicRow/CreateNicRow.js, src/components/CreateNicRow/tests/CreateNicRow.test.js
Currently when vm is missing a namespace we do not show any nic, we want to show all namespaces when not namespace is defined.
Ref: https://github.com/kubevirt/web-ui/pull/265
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1687917
=> Do not filter by namespace if vm is missing a namespace

src/components/StorageOverview/Capacity/Capacity.js, src/components/StorageOverview/Capacity/fixtures/Capacity.fixture.js, src/components/StorageOverview/Capacity/tests/Capacity.test.js, src/components/StorageOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap, src/components/StorageOverview/StorageOverview.js, src/components/StorageOverview/fixtures/StorageOverview.fixture.js
Added Capacity card to show 'Total capacity' in the form of a donut chart.
Tasks yet to be done as suggested by @julienlim@redhat.com -
1. Change the font of 'Total Capacity' title to a smaller one. The text should be smaller than the card title 'Capacity'.
2. Change GB to GiB.
How do I go about it?
These changes will be sent in a following patch.
Also, I'll send a PR in kubevirt/web-ui for the same and reference this there.
=> Adding Capacity Card to Storage Overview

src/components/ClusterOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap, src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap, src/components/Dashboard/Capacity/CapacityItem.js, src/components/Dashboard/Capacity/tests/__snapshots__/CapacityItem.test.js.snap, src/components/StorageOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap, src/utils/tests/utils.test.js, src/utils/utils.js
Changes done-
1. Font size of 'Total capacity' reduced as it shouldn't be larger than the card title. This also maintains consistency across cards in terms of aesthetics.
2. Units changed from GB to GiB and so on.
Before-
After-
=> Change Font size and Units in Capacity card

sass/_components.scss, sass/components/Dashboard/events.scss, src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap, src/components/Dashboard/Events/EventsBody.js, src/components/Dashboard/Events/fixtures/EventsBody.fixture.js, src/components/Dashboard/Events/tests/EventsBody.test.js, src/components/Dashboard/Events/tests/__snapshots__/EventsBody.test.js.snap, src/components/StorageOverview/Events/Events.js, src/components/StorageOverview/Events/fixtures/Events.fixture.js, src/components/StorageOverview/Events/tests/Events.test.js, src/components/StorageOverview/Events/tests/__snapshots__/Events.test.js.snap, src/components/StorageOverview/StorageOverview.js, src/components/StorageOverview/fixtures/StorageOverview.fixture.js, src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
ref: https://github.com/kubevirt/web-ui/pull/275
=> Added events card

sass/_components.scss, sass/components/ClusterOverview/cluster-overview.scss, sass/components/Dashboard/alert.scss, src/components/ClusterOverview/Alerts/Alerts.js, src/components/ClusterOverview/Alerts/fixtures/Alerts.fixture.js, src/components/ClusterOverview/Alerts/tests/Alerts.test.js, src/components/ClusterOverview/Alerts/tests/__snapshots__/Alerts.test.js.snap, src/components/ClusterOverview/Alerts/utils.js, src/components/ClusterOverview/ClusterOverview.js, src/components/ClusterOverview/fixtures/ClusterOverview.fixture.js, src/components/Dashboard/Alert/AlertItem.js, src/components/Dashboard/Alert/AlertsBody.js, src/components/Dashboard/Alert/fixtures/AlertItem.fixture.js, src/components/Dashboard/Alert/fixtures/AlertsBody.fixture.js, src/components/Dashboard/Alert/tests/AlertItem.test.js, src/components/Dashboard/Alert/tests/AlertsBody.test.js, src/components/Dashboard/Alert/tests/__snapshots__/AlertItem.test.js.snap, src/components/Dashboard/Alert/tests/__snapshots__/AlertsBody.test.js.snap, src/selectors/prometheus/alerts.js, src/selectors/prometheus/index.js
According to design we should have a dropdown which would allow filtering alerts by severity. Severity is defined by labels and label values can be anything so its up to alert creator to set the key and value. For this reason Im not adding dropdown yet. I try to recognize critical alerts by looking for label `severity: critical`. All others are evaluated as `warning` severity
=> Add Alerts Card

src/components/ClusterOverview/Capacity/Capacity.js, src/components/ClusterOverview/Capacity/fixtures/Capacity.fixture.js, src/components/ClusterOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap, src/components/ClusterOverview/Utilization/Utilization.js, src/components/ClusterOverview/Utilization/fixtures/Utilization.fixture.js, src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
and refactor prometheus queries for disk capacity so they
can be reused for utilization.
=> Utilization: Add Disk Usage chart

src/components/ClusterOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap, src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap, src/utils/tests/utils.test.js, src/utils/utils.js
@AyushAmbastha changing storage units to tectonic ones as suggested by @andybraren in https://github.com/kubevirt/web-ui-components/pull/318#issuecomment-481282991 and network to MBps format
=> Align byte units to tectonic ones.

src/selectors/host/selectors.js, src/utils/status/host/hostStatus.js
This fixes the problem when retrieving host status when there is no host.status data available
=> Add default host status when host does not have status data

sass/_components.scss, sass/components/StorageOverview/top-consumer.scss, src/components/StorageOverview/StorageOverview.js, src/components/StorageOverview/TopConsumers/TopConsumers.js, src/components/StorageOverview/TopConsumers/fixtures/TopConsumers.fixture.js, src/components/StorageOverview/TopConsumers/tests/TopConsumers.test.js, src/components/StorageOverview/TopConsumers/tests/__snapshots__/TopConsumers.test.js.snap, src/components/StorageOverview/fixtures/StorageOverview.fixture.js, src/selectors/prometheus/storage.js, src/utils/utils.js
ref: https://github.com/kubevirt/web-ui/pull/298
=> Added top consumer card for storage dashboard

src/constants/storage.js
CAPACITY_STORAGE_TOTAL_DEFAULT_QUERY
UTILIZATION_STORAGE_USED_DEFAULT_QUERY
=> Fix disk capacity prometheus metrics

src/components/ClusterOverview/Utilization/Utilization.js, src/components/ClusterOverview/Utilization/fixtures/Utilization.fixture.js, src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap, src/components/Dashboard/Utilization/UtilizationItem.js, src/constants/storage.js
Implemented as "best-effort", I do not have access to a Ceph environment.
=> Utilization: Disk IO RW chart

src/components/BareMetalHosts/BaremetalHostStatus.js, src/utils/status/host/hostStatus.js
This allows to derive host status based on status of other related
resources (machine/node)
Ref https://github.com/kubevirt/web-ui/pull/308
=> Enhance getHostStatus with additional resources

src/components/BareMetalHosts/fixtures/BaremetalHostStatus.fixture.js, src/components/BareMetalHosts/tests/BaremetalHostStatus.test.js, src/components/BareMetalHosts/tests/__snapshots__/BaremetalHostStatus.test.js.snap, src/utils/status/host/constants.js
Adding 3 new provisioning states:
- match profile (progress state)
- provisioning error (error state)
- power management error (error state)
=> Add new host states

sass/components/Dashboard/alert.scss, sass/components/Dashboard/capacity.scss, sass/components/Dashboard/health.scss, sass/components/StorageOverview/data-resiliency.scss, src/components/ClusterOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap, src/components/Dashboard/Capacity/CapacityItem.js, src/components/Dashboard/Capacity/tests/__snapshots__/CapacityItem.test.js.snap, src/components/StorageOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
=> Alignment and Color change

sass/components/ClusterOverview/health.scss, sass/components/Dashboard/consumers.scss, sass/components/Dashboard/dashboard.scss, sass/components/Dashboard/events.scss, sass/components/Dashboard/utilization.scss, src/components/ClusterOverview/Compliance/tests/__snapshots__/Compliance.test.js.snap, src/components/ClusterOverview/Events/tests/__snapshots__/Events.test.js.snap, src/components/ClusterOverview/Health/HealthBody.js, src/components/ClusterOverview/Health/tests/__snapshots__/Health.test.js.snap, src/components/ClusterOverview/Health/tests/__snapshots__/HealthBody.test.js.snap, src/components/ClusterOverview/Inventory/tests/__snapshots__/Inventory.test.js.snap, src/components/ClusterOverview/TopConsumers/tests/__snapshots__/TopConsumers.test.js.snap, src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap, src/components/Dashboard/DashboardCard/DashboardCardTitleHelp.js, src/components/Dashboard/DashboardCard/tests/__snapshots__/DashboardCardTitleHelp.test.js.snap, src/components/Dashboard/tests/__snapshots__/Dashboard.api.test.js.snap, src/components/StorageOverview/Events/tests/__snapshots__/Events.test.js.snap, src/components/StorageOverview/Inventory/tests/__snapshots__/Inventory.test.js.snap, src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
=> fix(events): style updates

src/components/Wizard/CreateVmWizard/CreateVmWizard.js
The confirmation message upon successful creation of a VM template was incorrectly being displayed as "Creation of VM was successful" as reported in [1]. This PR corrects the creation text to display "Creation of VM template was successful".
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1697816
=> Correct creation text for VM templates

src/components/BareMetalHosts/BaremetalHostStatus.js, src/components/BareMetalHosts/StatusComponents.js, src/components/BareMetalHosts/fixtures/BaremetalHostStatus.fixture.js, src/components/BareMetalHosts/fixtures/StatusComponents.fixture.js, src/components/BareMetalHosts/tests/StatusComponents.test.js, src/components/BareMetalHosts/tests/__snapshots__/BaremetalHostStatus.test.js.snap, src/components/BareMetalHosts/tests/__snapshots__/StatusComponents.test.js.snap
This adds a temporary placeholder link which should in future point
to dialog which lets user register a newly discovered host
=> Render Add Host link as host status when in discovered state

src/components/Dashboard/Utilization/UtilizationItem.js
@rawagner @suomiy sometime value provided by prometheus is null on the particular timestamp. So if that's the case the storage dashboard is breaking.
=> check if value is null for utilization graph

src/components/StorageOverview/DataResiliency/DataResiliency.js
due to the lag in updation of values for `totalPg` and `cleanAndActivePg` the progress percentage gets calculated above 100% sometimes.
=> bug fix: progress bar showing resiliency percentage above 100%

sass/_components.scss
this import is not needed because of dba7d0e34f59924b90538b693e6cc16da5d1ca93
=> remove superflous scss import

src/components/StorageOverview/TopConsumers/TopConsumers.js, src/selectors/prometheus/storage.js
Description - The x-axis was not plotting the time in sequence if the timestamps aren't same for all namespaces for top projects card.
Before : 
After fixing:
=> Fixed the x-axis sequence issue for top projects card

src/components/Details/VmDetails/VmDetails.js
If the user entered values into fields in the edit mode of the VM details screen, clicked the Cancel button, and then re-entered edit mode, the previously entered values would still be populated. This PR backs up the saved values before entering edit mode and restores them if editing is cancelled.
Bug: https://bugzilla.redhat.com/1698474
=> Drop VM detail edit values on cancel

sass/components/ClusterOverview/health.scss, sass/components/Dashboard/capacity.scss, sass/components/Dashboard/detail.scss, sass/components/Dashboard/events.scss, sass/components/StorageOverview/data-resiliency.scss, src/components/ClusterOverview/Details/tests/__snapshots__/Details.test.js.snap, src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap, src/components/Dashboard/Details/DetailsBody.js, src/components/Dashboard/Details/tests/__snapshots__/DetailsBody.test.js.snap, src/components/StorageOverview/Capacity/Capacity.js, src/components/StorageOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap, src/components/StorageOverview/Details/tests/__snapshots__/Details.test.js.snap, src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
backport of https://github.com/kubevirt/web-ui-components/pull/383
=> css updates for details/charts (#383)

src/components/Dashboard/Utilization/UtilizationItem.js, src/components/StorageOverview/Utilization/Utilization.js, src/components/StorageOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap, src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
With these changes, performance card will look like -
=> plotted y values for performance card graphs

src/config/index.js, src/k8s/objects/v2v/vmware/conversionPod.js, src/k8s/objects/v2v/vmware/vmWareDeployment.js, src/k8s/requests/v2v/startV2VvmwareController.js
=> v2v: Compose image name dynamically

src/components/Table/EditableDraggableTable.js, src/components/Table/TableFactory.js, src/components/Wizard/CreateVmWizard/CreateVmWizard.js, src/components/Wizard/CreateVmWizard/NetworksTab.js, src/components/Wizard/CreateVmWizard/StorageTab.js, src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js, src/components/Wizard/CreateVmWizard/tests/NetworksTab.test.js, src/components/Wizard/CreateVmWizard/tests/StorageTab.test.js
https://bugzilla.redhat.com/show_bug.cgi?id=1646953
=> Delete new row when cancel is clicked

src/k8s/requests/v2v/constants.js
The source .tar already contains the "vmware-vix-disklib-distrib" directory.
=> Fix vddk mount path

src/components/Table/EditableDraggableTable.js, src/components/Table/TableFactory.js, src/components/Wizard/CreateVmWizard/CreateVmWizard.js, src/components/Wizard/CreateVmWizard/NetworksTab.js, src/components/Wizard/CreateVmWizard/StorageTab.js, src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js, src/components/Wizard/CreateVmWizard/tests/NetworksTab.test.js, src/components/Wizard/CreateVmWizard/tests/StorageTab.test.js
Disable back/next buttons while editing table
https://bugzilla.redhat.com/show_bug.cgi?id=1646953
backport of https://github.com/kubevirt/web-ui-components/pull/430
=> Delete new row when cancel is clicked (#430)

src/components/Details/VmDetails/VmDetails.js, src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap, src/k8s/request.js, src/selectors/vmi/selectors.js
This PR does the following:
- Changes the "FQDN" label to "Hostname" in the VM overview tab
- If cloud init is used and hostname field is populated, sets vmi.spec.hostname to the hostname provided
- Sets vmi.spec.hostname to the VM name is cloud init isn't being used or the hostname field is empty
Bug: https://bugzilla.redhat.com/1688124
=> Correct hostname display in VM overview tab

src/components/Wizard/CreateVmWizard/NetworksTab.js, src/components/Wizard/CreateVmWizard/strings.js
backport of https://github.com/kubevirt/web-ui-components/pull/466
=> Improve empty network name message

config/cosmos.webpack.config.js, config/jest.config.js, config/jest.style.mock.js, package.json, sass/components/Status/status.scss, src/components/BareMetalHosts/StatusComponents.js, src/components/BareMetalHosts/tests/__snapshots__/StatusComponents.test.js.snap, src/components/ClusterOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap, src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap, src/components/Dashboard/Capacity/tests/__snapshots__/CapacityItem.test.js.snap, src/components/Dashboard/Utilization/tests/__snapshots__/UtilizationBody.test.js.snap, src/components/Dashboard/Utilization/tests/__snapshots__/UtilizationItem.test.js.snap, src/components/NodeStatus/NodeStatus.js, src/components/Status/Status.js, src/components/Status/fixtures/Status.fixture.js, src/components/StorageOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap, src/components/StorageOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap, yarn.lock
Currently BareMetalHosts Error status is broken.
-  Fix use of PF4 popover.
-  Syncing with `openshift/console` to patternfly-4 core version `3.16` from `1.43.x`.
Notes:
-  patternfly-4 v `1.x` has a broken `Popover`.
-  web-ui version of pf4 react is currently 2.4.1:
https://github.com/kubevirt/web-ui/blob/master/frontend/package.json#L63
- openshift console use 3.16.16:
https://github.com/openshift/console/blob/master/frontend/package.json#L66
Screenshot:
=> Fix baremetal status popover

src/components/Wizard/CreateVmWizard/CreateVmWizard.js, src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap
https://bugzilla.redhat.com/show_bug.cgi?id=1710888
=> Do not close Create VM Wizard when clicked outside of modal

src/components/Wizard/CreateVmWizard/stateUpdate/providers/prefillVmStateUpdate.js
- Once operating system is picked, Operating system for another VM is now detected
https://bugzilla.redhat.com/show_bug.cgi?id=1710932
this is fixed by https://github.com/kubevirt/web-ui-components/pull/474 in master
=> fix os picking

src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap, src/components/Wizard/CreateVmWizard/validations/vmSettingsTabValidation.js, src/utils/validations.js
backport of https://github.com/kubevirt/web-ui-components/pull/476
https://bugzilla.redhat.com/show_bug.cgi?id=1710775
=> Do not allow floats as memory value

src/components/Wizard/CreateVmWizard/stateUpdate/providers/prefillVmStateUpdate.js
- Once operating system is picked, Operating system for another VM is now detected
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1710932
=> fix: reset OS when re-selecting VM for import

src/k8s/migrate.js, src/k8s/tests/migrate.test.js, src/tests/k8s.js
backport of https://github.com/kubevirt/web-ui-components/pull/491
https://bugzilla.redhat.com/show_bug.cgi?id=1715050
=> Use k8s generateName for migration objects

src/components/Wizard/CreateVmWizard/initialState/providers/vmWareInitialState.js, src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/VMWareImportProvider.js, src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/constants.js, src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/fixtures/VMWareImportProvider.fixture.js, src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/tests/VMWareImportProvider.test.js, src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/tests/__snapshots__/VMWareImportProvider.test.js.snap, src/components/Wizard/CreateVmWizard/stateUpdate/providers/vmWareStateUpdate.js, src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap, src/k8s/requests/v2v/createV2VvmwareObject.js, src/k8s/requests/v2v/importVmware.js, src/k8s/tests/request.test.js, src/selectors/v2v/selectors.js, src/utils/patches.js, src/utils/tests/patches.test.js
This PR fixes an issue where vCenter credentials are not saved unless the create VM wizard is completed, regardless of success or failure. These changes cause the `kubevirt.io/temporary` label to be removed from the secret if the "Remember vCenter credentials" box is checked and adds the label with a value of true if the "Remember vCenter credentials" box is unchecked; however, these changes are only made if the connection check is successful.
Bug: https://bugzilla.redhat.com/1714004
Depends on: https://github.com/kubevirt/web-ui/pull/399
=> Fix save vCenter credentials functionality

sass/components/Dashboard/capacity.scss, src/components/StorageOverview/Capacity/Capacity.js, src/components/StorageOverview/Capacity/fixtures/Capacity.fixture.js, src/components/StorageOverview/Capacity/strings.js, src/components/StorageOverview/Capacity/tests/Capacity.test.js, src/components/StorageOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap, src/constants/storage.js
Implemented the dropdown options for the Capacity card.
1. Total Capacity
2. Requested vs Used
3. VMs vs Pods
The queries haven't been tested yet and will be changed, if needed.
=> Capacity Card Dropdown

src/components/Wizard/CreateVmWizard/CreateVmWizard.js
Firehose can be wrapped by react.memo within caller-context
=> Fix Firehose propType

src/utils/tests/validation.test.js, src/utils/validations.js
The dot character is not allowed in a subdomain value as the dot character is the delimiter between subdomain values.
=> Remove dot character from DNS-1123 validation

src/components/Wizard/CreateVmWizard/CreateVmWizard.js, src/components/Wizard/CreateVmWizard/initialState/vmSettingsTabInitialState.js
The V2V Import VMware option is supposed to be rendered just in case
that related infrastructure is deployed on the cluster.
In other words, check for presence of V2VVMware CRD is introduced.
As we have just a single provider (VMware) so far, the higher-level
"Import"-provision type is not rendered if the CRD is missing.
=> Create VM Wizard: conditionally rendered Import provision source

src/components/Dialog/CloneDialog/CloneDialog.js, src/components/Dialog/CloneDialog/fixtures/CloneDialog.fixture.js, src/components/Dialog/CloneDialog/index.js, src/components/Dialog/CloneDialog/tests/CloneDialog.test.js, src/components/Dialog/CloneDialog/tests/__snapshots__/CloneDialog.test.js.snap
bz: https://bugzilla.redhat.com/show_bug.cgi?id=1726193
sibling PR: https://github.com/kubevirt/web-ui/pull/416
=> CloneDialog: support non-admin users

src/components/TemplateSource/TemplateSource.js, src/components/Wizard/CreateVmWizard/constants.js, src/components/Wizard/CreateVmWizard/stateUpdate/vmSettingsTabStateUpdate.js, src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap, src/components/Wizard/CreateVmWizard/validations/vmSettingsTabValidation.js, src/constants/index.js, src/utils/templates.js, src/utils/validations.js
bug: https://bugzilla.redhat.com/show_bug.cgi?id=1687782
=> validate template sources with missing DataVolume

src/components/Form/FormFactory.js, src/components/Wizard/CreateVmWizard/StorageTab.js, src/components/Wizard/CreateVmWizard/tests/StorageTab.test.js, src/utils/grammar.js, src/utils/strings.js, src/utils/tests/validation.test.js, src/utils/validations.js
bug: https://bugzilla.redhat.com/show_bug.cgi?id=1710901
=> make DNS1123 validation more verbose

src/components/Wizard/CreateVmWizard/CreateVmWizard.js, src/constants/index.js, src/k8s/clone.js, src/k8s/request.js, src/k8s/vmBuilder.js, src/selectors/configmap/index.js, src/selectors/configmap/sc-defaults.js, src/selectors/dv/selectors.js, src/selectors/index.js, src/selectors/pvc/selectors.js
The `kubevirt-storage-class-defaults` ConfigMap is read for `accessMode` and `volumeMode` defaults when creating a DataVolume.
Sibling PR: https://github.com/openshift/console/pull/2200
ConfigMap example:
```
kind: ConfigMap
apiVersion: v1
metadata:
name: kubevirt-storage-class-defaults
namespace: openshift
data:
accessMode: ReadWriteOnce
volumeMode: Filesystem
local-sc.accessMode: ReadWriteOnce
local-sc.volumeMode: Filesystem
nfs-sc.accessMode: ReadWriteMany
nfs-sc.volumeMode: Filesystem
```
=> Use SC defaults for DV creation

src/k8s/requests/v2v/constants.js, src/k8s/requests/v2v/startV2VvmwareController.js
More safe to avoid unrelated modifications.
Follow-up for #507
=> v2v: move v2v-vmware ConfigMap to kubevirt-hyperconverged namespace

src/components/Wizard/CreateVmWizard/stateUpdate/providers/vmWareStateUpdate.js, src/k8s/requests/v2v/constants.js, src/k8s/requests/v2v/importVmware.js, src/selectors/serviceaccount/index.js, src/selectors/serviceaccount/serviceaccount.js, src/utils/utils.js
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1721018
=> v2v: Wait for ServiceAccount before creating conversion pod

src/components/Wizard/CreateVmWizard/StorageTab.js, src/components/Wizard/CreateVmWizard/constants.js, src/components/Wizard/CreateVmWizard/stateUpdate/providers/prefillVmStateUpdate.js, src/k8s/objects/v2v/vmware/conversionPod.js, src/k8s/request.js, src/k8s/requests/v2v/constants.js, src/k8s/requests/v2v/importVmware.js, src/selectors/v2v/selectors.js
The `v2v-vmware` ConfigMap is extended for new `vddk-init-image` key referring image built by cluster user/admin for the [VMware VDDK library](https://www.vmware.com/support/developer/vddk/) based on instructions in Kubevirt's documentation.
The image is used for a side-car container providing the library to the conversion pod,
replacing former vddk-pvc created once per-namespace.
---
- once per cluster, create a `vddk-init` container image, see instructions in https://github.com/oVirt/v2v-conversion-host/commit/bf8bd0a91c3ad67f285c55fe831105c29647db45
- `oc edit configmap v2v-vmware -n kubevirt-hyperconverged`
- under `data:` section, add new entry based on the first step above:
```
vddk-init-image: your.registry/vddk-init:latest
```
Please note, initial version of the `v2v-vmware` …
=> Deploy VDDK as side-car container

src/components/Wizard/CreateVmWizard/CreateVmWizard.js
This PR enables the "Close" button in the create VM wizard regardless of whether creation succeeded or failed.
Bug: https://bugzilla.redhat.com/1721454
=> Enable close button on failed VM creation in Wizard

src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap, src/components/Wizard/CreateVmWizard/validations/vmSettingsTabValidation.js, src/utils/validations.js
This PR adds hostname validation to the cloud-init settings section of the create VM/template wizard.
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1648321
=> Validate hostname in cloud-init settings

src/components/Wizard/CreateVmWizard/CreateVmWizard.js, src/k8s/request.js, src/k8s/requests/index.js, src/k8s/requests/storageClass/constants.js, src/k8s/requests/storageClass/index.js, src/k8s/requests/storageClass/storageClassConfigMap.js, src/k8s/requests/v2v/constants.js, src/k8s/requests/v2v/importVmware.js, src/k8s/requests/v2v/startV2VvmwareController.js, src/k8s/requests/v2v/vmwareConfigMap.js
Fixes issue with changing location of ConfigMaps in different releases.
The `kubevirt-storage-class-defaults` ConfigMap is attempted to be retrieved from the `openshift-cnv` first, then from `openshift` in case of error.
The `v2v-vmware` ConfigMap is read from `openshift-cnv` namespace first, then from `kubevirt-hyperconverged`.
=> Namespaces for kubevirt-storage-class-defaults and v2v-vmware

src/selectors/vmi/selectors.js
Enhanced to deal with both `ipAddress` and `ipAddresses`,
children of `vmi.status.interfaces`.
More info: https://kubevirt.io/api-reference/master/definitions.html#_v1_virtualmachineinstancenetworkinterface
=> Enhance getVmiIpAddresses() function

src/k8s/index.js, src/k8s/requests/v2v/correctVCenterSecretLabels.js, src/k8s/requests/v2v/createV2VvmwareObject.js, src/k8s/requests/v2v/importVmware.js, src/k8s/requests/v2v/index.js, src/k8s/requests/v2v/startV2VvmwareController.js
- add secret owner references
- move selectors for clearer approach
- support unit when creating PVCs
- let startV2VVMWareController behave like a promise
required by https://github.com/openshift/console/pull/2964
=> export v2v request functions + few fixes

src/components/Wizard/CreateVmWizard/stateUpdate/providers/prefillVmStateUpdate.js, src/k8s/objects/v2v/vmware/conversionPod.js, src/k8s/requests/v2v/constants.js, src/k8s/requests/v2v/importVmware.js, src/selectors/pvc/selectors.js
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1756328
=> v2v-conversion-pod: Use volumeDevices for Block volumeMode

src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/VMWareImportProvider.js, src/components/Wizard/CreateVmWizard/stateUpdate/providers/prefillVmStateUpdate.js, src/k8s/objects/v2v/vmware/conversionPod.js, src/k8s/requests/v2v/constants.js, src/k8s/requests/v2v/importVmware.js, src/k8s/requests/v2v/startV2VvmwareController.js, src/selectors/pvc/selectors.js
Backport of: #557 
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1756328
=> Backport 557, BZ 1756328: Use volumeDevices for Block volumeMode

config/babel.config.js, package.json, yarn.lock
Fixes https://github.com/kubevirt/web-ui-components/issues/571 for kubevirt and OpenShift console upstream.  See this issue: https://bugzilla.redhat.com/show_bug.cgi?id=1767853
fyi - @spadgett @rhamilto
=> fix(plugins): add spread operator plugin for edge support

src/k8s/request.js
Add a default value to the `getSetting` method used in `createVmTemplate` to make it similar to the `getSetting` method used in `createVM`
See discussion here:
https://github.com/openshift/console/pull/3355#pullrequestreview-315615211
=> add default value to getsettings
